name = "fastpbkdf2_ada"
description = "Binding and an Ada wrapper to fastpbkdf2"
version = "1.0.0"

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

[[depends-on]]
openssl = "~1.1.0"